# Generated by Django 2.0.2 on 2018-03-19 12:07

import django.contrib.postgres.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0007_auto_20180319_1025'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'ordering': ('parameter_type__order',),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='name')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='identifier')),
                ('auto_generated', models.BooleanField(help_text='Values of this parameter type can be generated from the asset', verbose_name='generated value')),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('positive_integer', 'PositiveInteger'), ('float_type', 'Float'), ('char', 'Character'), ('boolean', 'Boolean'), ('array', 'Array')], max_length=100, verbose_name='data type')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ArrayParameter',
            fields=[
                ('baseparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parameters.BaseParameter')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None, verbose_name='value')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('parameters.baseparameter',),
        ),
        migrations.CreateModel(
            name='BooleanParameter',
            fields=[
                ('baseparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parameters.BaseParameter')),
                ('value', models.BooleanField(verbose_name='value')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('parameters.baseparameter',),
        ),
        migrations.CreateModel(
            name='CharParameter',
            fields=[
                ('baseparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parameters.BaseParameter')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('parameters.baseparameter',),
        ),
        migrations.CreateModel(
            name='FloatParameter',
            fields=[
                ('baseparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parameters.BaseParameter')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('parameters.baseparameter',),
        ),
        migrations.CreateModel(
            name='IntegerParameter',
            fields=[
                ('baseparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parameters.BaseParameter')),
                ('value', models.IntegerField(verbose_name='value')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('parameters.baseparameter',),
        ),
        migrations.CreateModel(
            name='PositiveIntegerParameter',
            fields=[
                ('baseparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parameters.BaseParameter')),
                ('value', models.PositiveIntegerField(verbose_name='value')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('parameters.baseparameter',),
        ),
        migrations.AddField(
            model_name='choice',
            name='parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.ParameterType'),
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parameters.ParameterType'),
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_parameters.baseparameter_set+', to='contenttypes.ContentType'),
        ),
    ]
