# Generated by Django 2.0.2 on 2018-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_auto_20180505_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertype',
            name='data_type',
            field=models.CharField(choices=[('integer', 'Integer'), ('positive_integer', 'PositiveInteger'), ('float_type', 'Float'), ('char', 'Character'), ('boolean', 'Boolean'), ('array', 'Char array')], max_length=100, verbose_name='data type'),
        ),
    ]
