# Generated by Django 2.0.8 on 2018-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_auto_20180505_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertype',
            name='es_fulltext',
            field=models.BooleanField(default=False, verbose_name='add to Elasticsearch fulltext'),
        ),
        migrations.AddField(
            model_name='parametertype',
            name='es_parameter',
            field=models.BooleanField(default=False, verbose_name='add as Elasticsearch parameter'),
        ),
    ]
