# Generated by Django 2.0.8 on 2018-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0006_auto_20180902_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertype',
            name='show_in_detail',
            field=models.BooleanField(default=True, verbose_name='Show in detailed outputs'),
        ),
    ]
