# Generated by Django 2.0.9 on 2018-10-15 11:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0007_parametertype_show_in_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrayparameter',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='charparameter',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='value'),
        ),
    ]
